INSERT INTO Pruebas (Nombre_Prueba, Descripcion, Metodo)
VALUES 
('Hemograma Completo', 'Análisis de la sangre para medir los niveles de diferentes componentes', 'Método automático'),
('Prueba de Glucosa', 'Mide el nivel de glucosa en sangre', 'Enzimático'),
('Hemograma Completo', 'Análisis de la sangre para medir los niveles de diferentes componentes', 'Método automático'),
('Prueba de Glucosa', 'Mide el nivel de glucosa en sangre', 'Enzimático'),
('Perfil Lipídico', 'Mide los niveles de colesterol y triglicéridos en la sangre', 'Espectrofotometría'),
('Prueba de Función Hepática', 'Evalúa el funcionamiento del hígado', 'Química Clínica'),
('Prueba de Función Renal', 'Evalúa el funcionamiento de los riñones', 'Método enzimático'),
('Prueba de Embarazo', 'Detecta la presencia de la hormona hCG', 'Inmunoensayo'),
('Prueba de Hormonas Tiroideas', 'Mide los niveles de T3, T4 y TSH en sangre', 'Radioinmunoensayo'),
('Prueba de VIH', 'Detecta la presencia del virus VIH en sangre', 'ELISA'),
('Prueba de Hepatitis B', 'Detecta la presencia del virus de la Hepatitis B', 'Inmunoensayo'),
('Prueba de Hepatitis C', 'Detecta la presencia del virus de la Hepatitis C', 'Inmunoensayo'),
('Prueba de Electroforesis de Proteínas', 'Separa las proteínas en una muestra de sangre o de orina', 'Electroforesis en gel'),
('Prueba de Coagulación', 'Mide el tiempo de coagulación de la sangre', 'Coagulometría'),
('Prueba de Gases en Sangre', 'Mide los niveles de oxígeno y dióxido de carbono en la sangre', 'Gasometría'),
('Prueba de Amonio', 'Mide la concentración de amonio en la sangre', 'Espectrofotometría'),
('Prueba de Ácido Úrico', 'Mide los niveles de ácido úrico en la sangre', 'Método enzimático'),
('Prueba de Calcio', 'Mide los niveles de calcio en la sangre', 'Química Clínica'),
('Prueba de Magnesio', 'Mide los niveles de magnesio en la sangre', 'Espectrofotometría'),
('Prueba de Fosfato', 'Mide los niveles de fosfato en la sangre', 'Método enzimático'),
('Prueba de Bilirrubina', 'Mide los niveles de bilirrubina en la sangre', 'Espectrofotometría'),
('Prueba de Hemoglobina Glicosilada', 'Mide los niveles de hemoglobina glicosilada (HbA1c) en la sangre', 'HPLC'),
('Prueba de Ferritina', 'Mide los niveles de ferritina en la sangre', 'Inmunoensayo'),
('Prueba de Vitamina D', 'Mide los niveles de vitamina D en la sangre', 'Quimioluminiscencia'),
('Prueba de Vitamina B12', 'Mide los niveles de vitamina B12 en la sangre', 'Radioinmunoensayo'),
('Prueba de Folato', 'Mide los niveles de folato en la sangre', 'Quimioluminiscencia'),
('Prueba de Ácido Fólico', 'Mide los niveles de ácido fólico en la sangre', 'Radioinmunoensayo'),
('Prueba de Proteína C Reactiva', 'Mide los niveles de proteína C reactiva (PCR) en la sangre', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-nucleares', 'Detecta anticuerpos contra el núcleo celular', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-citrulinados', 'Detecta anticuerpos anti-citrulinados (anti-CCP)', 'ELISA'),
('Prueba de Anticuerpos Anti-DNA', 'Detecta anticuerpos anti-DNA', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-Ro', 'Detecta anticuerpos anti-Ro (SS-A)', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-La', 'Detecta anticuerpos anti-La (SS-B)', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Sm', 'Detecta anticuerpos anti-Sm', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-RNP', 'Detecta anticuerpos anti-RNP', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Scl-70', 'Detecta anticuerpos anti-Scl-70', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Jo-1', 'Detecta anticuerpos anti-Jo-1', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-histonas', 'Detecta anticuerpos anti-histonas', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-fosfolípidos', 'Detecta anticuerpos anti-fosfolípidos', 'ELISA'),
('Prueba de Anticuerpos Anti-mitocondriales', 'Detecta anticuerpos anti-mitocondriales', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-tiroglobulina', 'Detecta anticuerpos anti-tiroglobulina', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-peroxidasa', 'Detecta anticuerpos anti-peroxidasa (anti-TPO)', 'Inmunoensayo'),
('Hemograma Completo', 'Análisis de la sangre para medir los niveles de diferentes componentes', 'Método automático'),
('Prueba de Glucosa', 'Mide el nivel de glucosa en sangre', 'Enzimático'),
('Hemograma Completo', 'Análisis de la sangre para medir los niveles de diferentes componentes', 'Método automático'),
('Prueba de Glucosa', 'Mide el nivel de glucosa en sangre', 'Enzimático'),
('Perfil Lipídico', 'Mide los niveles de colesterol y triglicéridos en la sangre', 'Espectrofotometría'),
('Prueba de Función Hepática', 'Evalúa el funcionamiento del hígado', 'Química Clínica'),
('Prueba de Función Renal', 'Evalúa el funcionamiento de los riñones', 'Método enzimático'),
('Prueba de Embarazo', 'Detecta la presencia de la hormona hCG', 'Inmunoensayo'),
('Prueba de Hormonas Tiroideas', 'Mide los niveles de T3, T4 y TSH en sangre', 'Radioinmunoensayo'),
('Prueba de VIH', 'Detecta la presencia del virus VIH en sangre', 'ELISA'),
('Prueba de Hepatitis B', 'Detecta la presencia del virus de la Hepatitis B', 'Inmunoensayo'),
('Prueba de Hepatitis C', 'Detecta la presencia del virus de la Hepatitis C', 'Inmunoensayo'),
('Prueba de Electroforesis de Proteínas', 'Separa las proteínas en una muestra de sangre o de orina', 'Electroforesis en gel'),
('Prueba de Coagulación', 'Mide el tiempo de coagulación de la sangre', 'Coagulometría'),
('Prueba de Gases en Sangre', 'Mide los niveles de oxígeno y dióxido de carbono en la sangre', 'Gasometría'),
('Prueba de Amonio', 'Mide la concentración de amonio en la sangre', 'Espectrofotometría'),
('Prueba de Ácido Úrico', 'Mide los niveles de ácido úrico en la sangre', 'Método enzimático'),
('Prueba de Calcio', 'Mide los niveles de calcio en la sangre', 'Química Clínica'),
('Prueba de Magnesio', 'Mide los niveles de magnesio en la sangre', 'Espectrofotometría'),
('Prueba de Fosfato', 'Mide los niveles de fosfato en la sangre', 'Método enzimático'),
('Prueba de Bilirrubina', 'Mide los niveles de bilirrubina en la sangre', 'Espectrofotometría'),
('Prueba de Hemoglobina Glicosilada', 'Mide los niveles de hemoglobina glicosilada (HbA1c) en la sangre', 'HPLC'),
('Prueba de Ferritina', 'Mide los niveles de ferritina en la sangre', 'Inmunoensayo'),
('Prueba de Vitamina D', 'Mide los niveles de vitamina D en la sangre', 'Quimioluminiscencia'),
('Prueba de Vitamina B12', 'Mide los niveles de vitamina B12 en la sangre', 'Radioinmunoensayo'),
('Prueba de Folato', 'Mide los niveles de folato en la sangre', 'Quimioluminiscencia'),
('Prueba de Ácido Fólico', 'Mide los niveles de ácido fólico en la sangre', 'Radioinmunoensayo'),
('Prueba de Proteína C Reactiva', 'Mide los niveles de proteína C reactiva (PCR) en la sangre', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-nucleares', 'Detecta anticuerpos contra el núcleo celular', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-citrulinados', 'Detecta anticuerpos anti-citrulinados (anti-CCP)', 'ELISA'),
('Prueba de Anticuerpos Anti-DNA', 'Detecta anticuerpos anti-DNA', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-Ro', 'Detecta anticuerpos anti-Ro (SS-A)', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-La', 'Detecta anticuerpos anti-La (SS-B)', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Sm', 'Detecta anticuerpos anti-Sm', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-RNP', 'Detecta anticuerpos anti-RNP', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Scl-70', 'Detecta anticuerpos anti-Scl-70', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Jo-1', 'Detecta anticuerpos anti-Jo-1', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-histonas', 'Detecta anticuerpos anti-histonas', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-fosfolípidos', 'Detecta anticuerpos anti-fosfolípidos', 'ELISA'),
('Prueba de Anticuerpos Anti-mitocondriales', 'Detecta anticuerpos anti-mitocondriales', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-tiroglobulina', 'Detecta anticuerpos anti-tiroglobulina', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-peroxidasa', 'Detecta anticuerpos anti-peroxidasa (anti-TPO)', 'Inmunoensayo'),
('Hemograma Completo', 'Análisis de la sangre para medir los niveles de diferentes componentes', 'Método automático'),
('Prueba de Glucosa', 'Mide el nivel de glucosa en sangre', 'Enzimático'),
('Hemograma Completo', 'Análisis de la sangre para medir los niveles de diferentes componentes', 'Método automático'),
('Prueba de Glucosa', 'Mide el nivel de glucosa en sangre', 'Enzimático'),
('Perfil Lipídico', 'Mide los niveles de colesterol y triglicéridos en la sangre', 'Espectrofotometría'),
('Prueba de Función Hepática', 'Evalúa el funcionamiento del hígado', 'Química Clínica'),
('Prueba de Función Renal', 'Evalúa el funcionamiento de los riñones', 'Método enzimático'),
('Prueba de Embarazo', 'Detecta la presencia de la hormona hCG', 'Inmunoensayo'),
('Prueba de Hormonas Tiroideas', 'Mide los niveles de T3, T4 y TSH en sangre', 'Radioinmunoensayo'),
('Prueba de VIH', 'Detecta la presencia del virus VIH en sangre', 'ELISA'),
('Prueba de Hepatitis B', 'Detecta la presencia del virus de la Hepatitis B', 'Inmunoensayo'),
('Prueba de Hepatitis C', 'Detecta la presencia del virus de la Hepatitis C', 'Inmunoensayo'),
('Prueba de Electroforesis de Proteínas', 'Separa las proteínas en una muestra de sangre o de orina', 'Electroforesis en gel'),
('Prueba de Coagulación', 'Mide el tiempo de coagulación de la sangre', 'Coagulometría'),
('Prueba de Gases en Sangre', 'Mide los niveles de oxígeno y dióxido de carbono en la sangre', 'Gasometría'),
('Prueba de Amonio', 'Mide la concentración de amonio en la sangre', 'Espectrofotometría'),
('Prueba de Ácido Úrico', 'Mide los niveles de ácido úrico en la sangre', 'Método enzimático'),
('Prueba de Calcio', 'Mide los niveles de calcio en la sangre', 'Química Clínica'),
('Prueba de Magnesio', 'Mide los niveles de magnesio en la sangre', 'Espectrofotometría'),
('Prueba de Fosfato', 'Mide los niveles de fosfato en la sangre', 'Método enzimático'),
('Prueba de Bilirrubina', 'Mide los niveles de bilirrubina en la sangre', 'Espectrofotometría'),
('Prueba de Hemoglobina Glicosilada', 'Mide los niveles de hemoglobina glicosilada (HbA1c) en la sangre', 'HPLC'),
('Prueba de Ferritina', 'Mide los niveles de ferritina en la sangre', 'Inmunoensayo'),
('Prueba de Vitamina D', 'Mide los niveles de vitamina D en la sangre', 'Quimioluminiscencia'),
('Prueba de Vitamina B12', 'Mide los niveles de vitamina B12 en la sangre', 'Radioinmunoensayo'),
('Prueba de Folato', 'Mide los niveles de folato en la sangre', 'Quimioluminiscencia'),
('Prueba de Ácido Fólico', 'Mide los niveles de ácido fólico en la sangre', 'Radioinmunoensayo'),
('Prueba de Proteína C Reactiva', 'Mide los niveles de proteína C reactiva (PCR) en la sangre', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-nucleares', 'Detecta anticuerpos contra el núcleo celular', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-citrulinados', 'Detecta anticuerpos anti-citrulinados (anti-CCP)', 'ELISA'),
('Prueba de Anticuerpos Anti-DNA', 'Detecta anticuerpos anti-DNA', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-Ro', 'Detecta anticuerpos anti-Ro (SS-A)', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-La', 'Detecta anticuerpos anti-La (SS-B)', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Sm', 'Detecta anticuerpos anti-Sm', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-RNP', 'Detecta anticuerpos anti-RNP', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Scl-70', 'Detecta anticuerpos anti-Scl-70', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-Jo-1', 'Detecta anticuerpos anti-Jo-1', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-histonas', 'Detecta anticuerpos anti-histonas', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-fosfolípidos', 'Detecta anticuerpos anti-fosfolípidos', 'ELISA'),
('Prueba de Anticuerpos Anti-mitocondriales', 'Detecta anticuerpos anti-mitocondriales', 'Inmunofluorescencia'),
('Prueba de Anticuerpos Anti-tiroglobulina', 'Detecta anticuerpos anti-tiroglobulina', 'Inmunoensayo'),
('Prueba de Anticuerpos Anti-peroxidasa', 'Detecta anticuerpos anti-peroxidasa (anti-TPO)', 'Inmunoensayo')